# Change these first
owner: iamlasse # Your GitHub organization or username, where this repository lives
repo: telekomupptime # The name of this repository

sites:
  - name: Telekomkollen Production
    url: https://app.telekomkollen.se
  - name: Telekomkollen Development
    url: https://dev.telekomkollen.se

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /telekomupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Telekomkollen Upptime"
  introMessage: Status for Telekomkollen Dashboard Pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
